Default: &defaults
  database: recipes.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: recipes_test.sqlite3
  <<: *defaults

Staging:
  database: recipes_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: recipes_production.sqlite3
  poolsize: 100
  <<: *defaults
